AMREX_HOME ?= ../../../../..
USE_EB =FALSE
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE
DEBUG      = FALSE

DIM        = 2
#DIM       = 3

COMP	   = gnu

#USE_PARTICLES = TRUE

USE_MPI    = FALSE
USE_OMP    = TRUE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv
